### PR TITLE
fix(splash-screen): avoid conditional downcast warning

### LINKED ISSUE #761: Conditional downcast from 'UIWindow?' to 'UIWindow' does nothing
https://github.com/ionic-team/capacitor-plugins/blob/3ec2008bc0311c837346ecbdd0afd105149b427a/splash-screen/ios/Plugin/SplashScreen.swift#L120

The line produces a warning while compiling an iOS application in Xcode 13.2.1.

### PR DESCRIPTION
**Pull request by riderx**
closes #761

### CODE REVIEW

File: splash-screen/ios/Plugin/SplashScreen.swift [hunk 1]
```diff
@@ -117,7 +117,7 @@ import Capacitor
     // Update the bounds for the splash image. This will also be called when
     // the parent view observers fire
     private func updateSplashImageBounds() {
-        var window: UIWindow? = UIApplication.shared.delegate?.window as? UIWindow
+        var window: UIWindow? = UIApplication.shared.delegate?.window
```
Comment (jcesarmobile) [inline splash-screen/ios/Plugin/SplashScreen.swift:120]: Thanks for the PR, but the code doesn't compile, I think it should look like this:
```suggestion
        var window: UIWindow? = UIApplication.shared.delegate?.window ?? nil
```

**Review by jcesarmobile — APPROVED** [review]
looks good, thanks!
